swagger: "2.0"
basePath: "/v1"
info:
  version: 1.0.0
  title: "Dentist Reservation"
  description: "Book an appointment with a dentist"
host: localhost:5003
schemes:
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
  - "text/plain"
paths:
  /timelots:
    get:
      tags:
        - "Appointments"
      summary: "Gets the available time slots"
      description: ""
      consumes: 
      - "application/json"
      produces: 
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Appointments"
        400:
          description: "Invalid status value"
   
  /timeslots/{timeslot}:
    post:
      tags: 
        - "Appointments"
      summary: "Reserve the timeslots by id"
      description: ""
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: timeslot
        in: path
        description: "id of timeslot that needs to be booked"
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: "OK"
          schema:
            type: string
        405:
          description: Invalid input
    get:
      tags:
        - "Appointments"
      summary: "Get the status of the timeslot by id"
      description: ""
      operationId: "uploadtimeslot"
      produces: 
      - "application/json"
      parameters:
        - name: "timeslot"
          in: "path"
          description: "ID of timeslot that needs to get status"
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: string
              # $ref: '#/definitions/Appointments'
        400:
          description: "Invalid Id of Time"
        404:
          description: "Time not found"
    
    delete:
      tags: 
        - "Appointments"
      summary: "cancelling appointment"
      description: ""
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: timeslot
        in: path
        description: id of timeslot that needs to be deleted
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: OK
          schema:
            type: string
        405:
          description: Invalid input
  /dentist/{dentist}:
    get:
      tags:
        - "Appointments"
      summary: "Get the available timeslots by the dentist name"
      description: ""
      produces: 
      - "application/json"
      parameters:
        - name: "dentist"
          in: "path"
          description: "Name of the dentist"
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Appointments"
        400:
          description: "Invalid Id of Time"
        404:
          description: "Time not found"
  /timeslotsdentist/{time}:
    get:
      tags:
        - "Appointments"
      summary: "Gets the available dentists by time"
      description: ""
      consumes: 
      - "application/json"
      produces: 
      - "application/json"
      parameters: 
        - name: "time"
          in: "path"
          description: "time of of the timeslot that you want to booked"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Appointments"
        400:
          description: "Invalid status value"
definitions:
  Appointments:
    type: object
    properties:
      id:
        type: integer
        format: int64
      time:
        type: string
      dentist:
        type: string
      status:
        type: string
